export interface FontPairing {
  id: string;
  primary: string;
  secondary: string;
  primaryAlt: string | null;
  secondaryAlt: string | null;
  description: string;
  tags: string[];
}

export const FONT_PAIRINGS: FontPairing[] = [
  {
    id: 'playfair-source',
    primary: 'Playfair Display',
    secondary: 'Source Sans 3',
    primaryAlt: null,
    secondaryAlt: null,
    description: 'Elegant serif headlines with clean sans-serif body text',
    tags: ['classic', 'editorial', 'luxury'],
  },
  {
    id: 'montserrat-merriweather',
    primary: 'Montserrat',
    secondary: 'Merriweather',
    primaryAlt: null,
    secondaryAlt: null,
    description: 'Geometric sans paired with a readable serif',
    tags: ['modern', 'balanced', 'professional'],
  },
  {
    id: 'inter-lora',
    primary: 'Inter',
    secondary: 'Lora',
    primaryAlt: null,
    secondaryAlt: null,
    description: 'Versatile UI sans with an elegant serif',
    tags: ['tech', 'clean', 'versatile'],
  },
  {
    id: 'raleway-roboto-slab',
    primary: 'Raleway',
    secondary: 'Roboto Slab',
    primaryAlt: null,
    secondaryAlt: null,
    description: 'Thin elegant sans with sturdy slab serif',
    tags: ['modern', 'bold', 'architectural'],
  },
  {
    id: 'dm-sans-dm-serif',
    primary: 'DM Sans',
    secondary: 'DM Serif Display',
    primaryAlt: null,
    secondaryAlt: null,
    description: 'Matching DM family for cohesive design',
    tags: ['cohesive', 'contemporary', 'editorial'],
  },
  {
    id: 'space-grotesk-libre',
    primary: 'Space Grotesk',
    secondary: 'Libre Baskerville',
    primaryAlt: null,
    secondaryAlt: null,
    description: 'Futuristic sans with traditional serif',
    tags: ['tech', 'contrast', 'striking'],
  },
  {
    id: 'outfit-crimson',
    primary: 'Outfit',
    secondary: 'Crimson Text',
    primaryAlt: null,
    secondaryAlt: null,
    description: 'Rounded geometric sans with warm serif',
    tags: ['friendly', 'warm', 'approachable'],
  },
  {
    id: 'jakarta-fraunces',
    primary: 'Plus Jakarta Sans',
    secondary: 'Fraunces',
    primaryAlt: null,
    secondaryAlt: null,
    description: 'Modern geometric with wonky optical serif',
    tags: ['creative', 'expressive', 'premium'],
  },
  {
    id: 'poppins-lora',
    primary: 'Poppins',
    secondary: 'Lora',
    primaryAlt: null,
    secondaryAlt: null,
    description: 'Geometric and friendly paired with elegant serif',
    tags: ['friendly', 'modern', 'balanced'],
  },
  {
    id: 'garamond-inter',
    primary: 'EB Garamond',
    secondary: 'Inter',
    primaryAlt: null,
    secondaryAlt: null,
    description: 'Classical serif headlines with modern sans body',
    tags: ['classic', 'refined', 'editorial'],
  },
  {
    id: 'futura-garamond',
    primary: 'Jost',
    secondary: 'EB Garamond',
    primaryAlt: 'Futura',
    secondaryAlt: 'Garamond',
    description: 'Geometric modernist with classical serif',
    tags: ['luxury', 'fashion', 'high-end'],
  },
  {
    id: 'avenir-bodoni',
    primary: 'Nunito',
    secondary: 'Libre Bodoni',
    primaryAlt: 'Avenir',
    secondaryAlt: 'Bodoni',
    description: 'Rounded humanist sans with high-contrast serif',
    tags: ['elegant', 'fashion', 'editorial'],
  },
  {
    id: 'helvetica-didot',
    primary: 'Inter',
    secondary: 'Playfair Display',
    primaryAlt: 'Helvetica',
    secondaryAlt: 'Didot',
    description: 'Neutral Swiss sans with dramatic modern serif',
    tags: ['luxury', 'magazine', 'sophisticated'],
  },
  {
    id: 'proxima-cooper',
    primary: 'Montserrat',
    secondary: 'Alfa Slab One',
    primaryAlt: 'Proxima Nova',
    secondaryAlt: 'Cooper Black',
    description: 'Clean sans with bold retro slab',
    tags: ['retro', 'bold', 'playful'],
  },
  {
    id: 'gotham-garamond',
    primary: 'Plus Jakarta Sans',
    secondary: 'EB Garamond',
    primaryAlt: 'Gotham',
    secondaryAlt: 'Garamond',
    description: 'Strong geometric sans with traditional serif',
    tags: ['corporate', 'professional', 'trustworthy'],
  },
  {
    id: 'futura-bodoni',
    primary: 'Jost',
    secondary: 'Libre Bodoni',
    primaryAlt: 'Futura',
    secondaryAlt: 'Bodoni',
    description: 'Bauhaus-inspired with Italian high-contrast serif',
    tags: ['art-deco', 'dramatic', 'luxury'],
  },
  {
    id: 'proxima-didot',
    primary: 'Montserrat',
    secondary: 'Playfair Display',
    primaryAlt: 'Proxima Nova',
    secondaryAlt: 'Didot',
    description: 'Modern geometric sans with Parisian serif',
    tags: ['chic', 'luxury', 'magazine'],
  },
  {
    id: 'gotham-helvetica',
    primary: 'Plus Jakarta Sans',
    secondary: 'Inter',
    primaryAlt: 'Gotham',
    secondaryAlt: 'Helvetica',
    description: 'Two neutral geometric sans for ultimate clean design',
    tags: ['minimal', 'corporate', 'clean'],
  },
];
