/**
 * Lightweight ISO 3166-1 alpha-2 → human-readable continent label mapping
 * used as the country sub-title in the Countries dashboard table.
 * Only countries we expect to surface in clinical-trial geographies are
 * curated; unknown codes return `null` so callers can choose their own
 * fallback (typically rendering nothing).
 */
const CONTINENT_BY_COUNTRY: Record<string, string> = {
  // North America
  US: 'North America',
  CA: 'North America',
  MX: 'North America',
  PR: 'North America',
  GT: 'North America',
  CR: 'North America',
  PA: 'North America',
  DO: 'North America',
  HN: 'North America',
  SV: 'North America',
  NI: 'North America',
  CU: 'North America',
  HT: 'North America',
  JM: 'North America',
  TT: 'North America',
  // South America
  BR: 'South America',
  AR: 'South America',
  CL: 'South America',
  CO: 'South America',
  PE: 'South America',
  VE: 'South America',
  UY: 'South America',
  PY: 'South America',
  EC: 'South America',
  BO: 'South America',
  GY: 'South America',
  SR: 'South America',
  // Europe
  GB: 'Europe',
  IE: 'Europe',
  FR: 'Europe',
  DE: 'Europe',
  ES: 'Europe',
  PT: 'Europe',
  IT: 'Europe',
  NL: 'Europe',
  BE: 'Europe',
  LU: 'Europe',
  CH: 'Europe',
  AT: 'Europe',
  DK: 'Europe',
  SE: 'Europe',
  NO: 'Europe',
  FI: 'Europe',
  IS: 'Europe',
  PL: 'Europe',
  CZ: 'Europe',
  SK: 'Europe',
  HU: 'Europe',
  RO: 'Europe',
  BG: 'Europe',
  GR: 'Europe',
  HR: 'Europe',
  SI: 'Europe',
  RS: 'Europe',
  EE: 'Europe',
  LV: 'Europe',
  LT: 'Europe',
  UA: 'Europe',
  BY: 'Europe',
  MD: 'Europe',
  RU: 'Europe',
  TR: 'Europe',
  AL: 'Europe',
  MK: 'Europe',
  BA: 'Europe',
  ME: 'Europe',
  XK: 'Europe',
  CY: 'Europe',
  MT: 'Europe',
  // Asia
  JP: 'Asia',
  CN: 'Asia',
  KR: 'Asia',
  IN: 'Asia',
  PK: 'Asia',
  BD: 'Asia',
  LK: 'Asia',
  TH: 'Asia',
  VN: 'Asia',
  ID: 'Asia',
  MY: 'Asia',
  SG: 'Asia',
  PH: 'Asia',
  TW: 'Asia',
  HK: 'Asia',
  MO: 'Asia',
  KZ: 'Asia',
  UZ: 'Asia',
  AZ: 'Asia',
  GE: 'Asia',
  AM: 'Asia',
  IR: 'Asia',
  IQ: 'Asia',
  IL: 'Asia',
  JO: 'Asia',
  LB: 'Asia',
  SY: 'Asia',
  SA: 'Asia',
  AE: 'Asia',
  QA: 'Asia',
  KW: 'Asia',
  BH: 'Asia',
  OM: 'Asia',
  YE: 'Asia',
  AF: 'Asia',
  NP: 'Asia',
  MM: 'Asia',
  KH: 'Asia',
  LA: 'Asia',
  MN: 'Asia',
  // Africa
  ZA: 'Africa',
  EG: 'Africa',
  NG: 'Africa',
  KE: 'Africa',
  ET: 'Africa',
  MA: 'Africa',
  TN: 'Africa',
  DZ: 'Africa',
  GH: 'Africa',
  UG: 'Africa',
  TZ: 'Africa',
  SN: 'Africa',
  CI: 'Africa',
  CM: 'Africa',
  ZW: 'Africa',
  ZM: 'Africa',
  AO: 'Africa',
  MZ: 'Africa',
  MG: 'Africa',
  RW: 'Africa',
  // Oceania
  AU: 'Oceania',
  NZ: 'Oceania',
  FJ: 'Oceania',
  PG: 'Oceania',
};

export function continentForCountry(
  countryCode: string | null | undefined,
): string | null {
  if (!countryCode) return null;
  return CONTINENT_BY_COUNTRY[countryCode.trim().toUpperCase()] ?? null;
}
