import { redirect } from 'next/navigation';
import Link from 'next/link';
import { ArrowLeft, Sparkles } from 'lucide-react';

import { createClient } from '@/lib/server';
import {
  generateBriefing,
  loadTodayBriefing,
  persistBriefing,
} from '@/lib/copilot/briefing-builder';
import { recordAudit } from '@/lib/copilot/audit';
import { Button } from '@/components/ui/button';
import { BriefingView } from '@/components/copilot/briefing/briefing-view';

export const dynamic = 'force-dynamic';

interface PageProps {
  searchParams: Promise<{ refresh?: string }>;
}

export default async function CopilotBriefingPage({ searchParams }: PageProps) {
  const supabase = await createClient();
  const { data: { user }, error } = await supabase.auth.getUser();
  if (error || !user) redirect('/auth/login');

  const { data: profile } = await supabase
    .from('profiles')
    .select('id, first_name, company_id, role')
    .eq('user_id', user.id)
    .maybeSingle();
  if (!profile?.company_id) redirect('/auth/login?reason=profile');

  const params = await searchParams;
  const refresh = params.refresh === '1';

  let briefing = refresh ? null : await loadTodayBriefing(supabase, user.id);
  let generated = false;

  if (!briefing) {
    const fresh = await generateBriefing({
      userId: user.id,
      userRole: profile.role ?? 'user',
      companyId: profile.company_id,
    });
    briefing = await persistBriefing(supabase, fresh, { refresh });
    generated = true;

    if (briefing) {
      await recordAudit(supabase, {
        userId: user.id,
        companyId: profile.company_id,
        agentId: 'briefing-curator',
        agentVersion: '1.0.0',
        action: 'briefing_generated',
        resourceKind: 'copilot_briefing',
        resourceId: briefing.id ?? undefined,
        details: { itemCount: briefing.items.length, refresh },
      });
    }
  }

  return (
    <div className="mx-auto max-w-4xl space-y-6 p-6">
      <header className="space-y-2">
        <Button asChild variant="ghost" size="sm" className="-ml-2 text-xs">
          <Link href="/protected/copilot">
            <ArrowLeft className="mr-1 h-3 w-3" />
            Command Center
          </Link>
        </Button>
        <div className="flex items-center justify-between gap-4">
          <div>
            <p className="text-xs font-normal uppercase tracking-wide text-muted-foreground">
              Morning briefing
            </p>
            <h1 className="flex items-center gap-2 text-2xl font-normal">
              <Sparkles className="h-5 w-5" style={{ color: 'var(--copilot-accent)' }} />
              Today
            </h1>
            <p className="text-sm text-muted-foreground">
              {briefing
                ? `${briefing.items.length} item${briefing.items.length === 1 ? '' : 's'} \u00B7 generated by ${briefing.agentId} v${briefing.agentVersion}`
                : 'No briefing available'}
            </p>
          </div>
          <Button asChild variant="outline" size="sm">
            <Link href="/protected/copilot/briefing?refresh=1">Refresh</Link>
          </Button>
        </div>
      </header>

      {briefing ? (
        <BriefingView briefing={briefing} pathname="/protected/copilot/briefing" generated={generated} />
      ) : (
        <p className="text-sm text-muted-foreground">
          The briefing service is unavailable right now. Try refreshing in a minute.
        </p>
      )}
    </div>
  );
}
