'use client';

import { useState, useTransition } from 'react';
import { Sparkles } from 'lucide-react';
import { toast } from 'sonner';

import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';

interface AiFinanceInsightsPanelProps {
  studyId: string;
  scope?:
    | 'dashboard'
    | 'budget'
    | 'invoices'
    | 'purchase_orders'
    | 'site_payments'
    | 'vendors'
    | 'forecast'
    | 'approvals';
  title?: string;
  description?: string;
}

type ApiOk = {
  insight?: string;
  error?: string;
  cached?: boolean;
  generatedAt?: string;
  nextRefreshAllowedAt?: string;
  tokensUsed?: number;
  cap?: number;
  retryAfterSec?: number;
};

export function AiFinanceInsightsPanel({
  studyId,
  scope = 'dashboard',
  title = 'AI Finance Insights',
  description = 'Generated by OpenAI from study-scoped finance context. Advisory only — no automatic changes are made.',
}: AiFinanceInsightsPanelProps) {
  const [insight, setInsight] = useState<string>('');
  const [generatedAt, setGeneratedAt] = useState<string | null>(null);
  const [nextRefreshAllowedAt, setNextRefreshAllowedAt] = useState<string | null>(null);
  const [tokensUsed, setTokensUsed] = useState<number | null>(null);
  const [cap, setCap] = useState<number | null>(null);
  const [lastFromCache, setLastFromCache] = useState(false);
  const [isPending, startTransition] = useTransition();

  const callApi = (forceRefresh: boolean) => {
    startTransition(async () => {
      try {
        const response = await fetch('/api/ai/finance-module-insights', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ studyId, scope, forceRefresh }),
        });
        const data = (await response.json()) as ApiOk;
        if (!response.ok || data.error) {
          toast.error(data.error ?? 'Failed to generate insight.');
          if (typeof data.retryAfterSec === 'number') {
            toast.message(`Try again in ${data.retryAfterSec}s.`);
          }
          return;
        }
        setInsight(data.insight ?? '');
        setLastFromCache(Boolean(data.cached));
        setGeneratedAt(data.generatedAt ?? new Date().toISOString());
        setNextRefreshAllowedAt(data.nextRefreshAllowedAt ?? null);
        setTokensUsed(typeof data.tokensUsed === 'number' ? data.tokensUsed : null);
        setCap(typeof data.cap === 'number' ? data.cap : null);
        if (data.cached) {
          toast.message('Showing cached insight (≤1h). Use Refresh to fetch a new one after cooldown.');
        }
      } catch {
        toast.error('Failed to reach AI service.');
      }
    });
  };

  return (
    <Card>
      <CardHeader>
        <CardTitle className="text-sm font-medium flex items-center gap-2">
          <Sparkles className="size-4 text-primary" />
          {title}
        </CardTitle>
        <CardDescription className="text-[11px]">{description}</CardDescription>
      </CardHeader>
      <CardContent>
        {insight ? (
          <div className="space-y-2">
            <p className="text-xs whitespace-pre-line">{insight}</p>
            {generatedAt ? (
              <p className="text-[10px] text-muted-foreground italic">
                {lastFromCache ? 'Cached result' : 'Generated'} {new Date(generatedAt).toLocaleString()}.
                {nextRefreshAllowedAt
                  ? ` Cache refreshes after ${new Date(nextRefreshAllowedAt).toLocaleTimeString()}.`
                  : null}{' '}
                Insights are advisory only and never modify financial records.
              </p>
            ) : null}
            {tokensUsed != null && cap != null ? (
              <p className="text-[10px] text-muted-foreground">
                Study token estimate today: {tokensUsed.toLocaleString()} / {cap.toLocaleString()} (resets daily on
                server process; advisory cap).
              </p>
            ) : null}
          </div>
        ) : (
          <p className="text-xs text-muted-foreground">
            Generate a concise narrative from the latest finance signals for this study.
          </p>
        )}
        <div className="mt-3 flex flex-wrap gap-2">
          <Button size="sm" className="text-xs" onClick={() => callApi(false)} disabled={isPending}>
            {isPending ? 'Working…' : insight ? 'Regenerate' : 'Generate insight'}
          </Button>
          <Button
            size="sm"
            variant="outline"
            className="text-xs"
            disabled={isPending}
            onClick={() => callApi(true)}
          >
            Refresh insights
          </Button>
        </div>
        <p className="mt-2 text-[10px] text-muted-foreground">
          Cached results reuse the prior answer for up to 1 hour. &quot;Refresh insights&quot; bypasses the cache after
          a 60s cooldown and still counts toward the daily token budget.
        </p>
      </CardContent>
    </Card>
  );
}
