-- Ensure directory role catalog seed data exists.
-- This re-runs the inserts from 20260335000000 with ON CONFLICT DO NOTHING
-- so it is safe to run even if data already exists.

INSERT INTO public.directory_role_categories (code, name, sort_order) VALUES
  ('sponsor', 'Sponsor organization', 10),
  ('cro', 'CRO', 20),
  ('site', 'Clinical site', 30),
  ('regulatory_ethics', 'Regulatory & ethics', 40),
  ('vendors', 'Vendors & service providers', 50),
  ('financial', 'Financial & contracting', 60),
  ('governance', 'Study governance & committees', 70),
  ('technology', 'Technology & systems', 80)
ON CONFLICT (code) DO NOTHING;

INSERT INTO public.directory_roles (category_id, name, sort_order)
SELECT c.id, r.name, r.ord FROM public.directory_role_categories c
INNER JOIN (VALUES
  -- sponsor
  ('sponsor', 'Chief Medical Officer (CMO)', 1),
  ('sponsor', 'VP Clinical', 2),
  ('sponsor', 'Clinical Program Director', 3),
  ('sponsor', 'Clinical Project Manager', 4),
  ('sponsor', 'Clinical Trial Manager', 5),
  ('sponsor', 'Director Clinical Operations', 6),
  ('sponsor', 'Medical Monitor', 7),
  ('sponsor', 'Safety Physician', 8),
  ('sponsor', 'Pharmacovigilance Manager', 9),
  ('sponsor', 'Regulatory Affairs Director', 10),
  ('sponsor', 'Regulatory Affairs Manager', 11),
  ('sponsor', 'Quality Assurance Director', 12),
  ('sponsor', 'Quality Assurance Auditor', 13),
  ('sponsor', 'Data Management Director', 14),
  ('sponsor', 'Clinical Data Manager', 15),
  ('sponsor', 'Biostatistics Director', 16),
  ('sponsor', 'Biostatistician', 17),
  ('sponsor', 'Clinical Systems Administrator', 18),
  ('sponsor', 'Project Manager (Sponsor)', 19),
  ('sponsor', 'Clinical Research Associate (Sponsor)', 20),
  ('sponsor', 'Clinical Trial Assistant (Sponsor)', 21),
  ('sponsor', 'Monitoring Manager (Sponsor)', 22),
  -- cro
  ('cro', 'Project Director', 1),
  ('cro', 'Project Manager (CRO)', 2),
  ('cro', 'Clinical Trial Manager', 3),
  ('cro', 'Clinical Research Associate (CRO)', 4),
  ('cro', 'In-House CRA (CRO)', 5),
  ('cro', 'Site Management Associate (SMA)', 6),
  ('cro', 'Clinical Trial Assistant (CTA)', 7),
  ('cro', 'Study Startup Specialist (SSU Specialist)', 8),
  ('cro', 'Regulatory Specialist', 9),
  ('cro', 'Clinical Data Manager', 10),
  ('cro', 'Biostatistician', 11),
  ('cro', 'Medical Writer', 12),
  ('cro', 'Safety Specialist', 13),
  ('cro', 'Vendor Manager', 14),
  ('cro', 'Monitoring Manager (CRO)', 15),
  -- site
  ('site', 'Principal Investigator (PI)', 1),
  ('site', 'Sub-Investigator', 2),
  ('site', 'Co-Investigator', 3),
  ('site', 'Study Coordinator', 4),
  ('site', 'Research Nurse', 5),
  ('site', 'Lead Study Coordinator', 6),
  ('site', 'Site Data Manager', 7),
  ('site', 'Site Regulatory Coordinator', 8),
  ('site', 'Pharmacist', 9),
  ('site', 'Lab Technician', 10),
  ('site', 'Radiology Technician', 11),
  ('site', 'Cath Lab Technician', 12),
  ('site', 'Device Specialist', 13),
  ('site', 'Research Assistant', 14),
  ('site', 'Fellow', 15),
  -- regulatory_ethics
  ('regulatory_ethics', 'IRB Chair', 1),
  ('regulatory_ethics', 'IRB Administrator', 2),
  ('regulatory_ethics', 'IRB Coordinator', 3),
  ('regulatory_ethics', 'Ethics Committee Member', 4),
  ('regulatory_ethics', 'Regulatory Agency Reviewer', 5),
  ('regulatory_ethics', 'Regulatory Agency Project Manager', 6),
  ('regulatory_ethics', 'Notified Body Representative', 7),
  -- vendors
  ('vendors', 'Central Lab Project Manager', 1),
  ('vendors', 'Imaging Core Lab Coordinator', 2),
  ('vendors', 'Data Safety Monitoring Board (DSMB) Member', 3),
  ('vendors', 'DSMB Chair', 4),
  ('vendors', 'Medical Adjudication Committee Member', 5),
  ('vendors', 'Clinical Events Committee (CEC) Member', 6),
  ('vendors', 'eClinical Systems Vendor Manager', 7),
  ('vendors', 'EDC Administrator', 8),
  ('vendors', 'Randomization / IWRS Manager', 9),
  ('vendors', 'Drug Supply Manager', 10),
  ('vendors', 'Logistics Manager', 11),
  ('vendors', 'Clinical Supplies Manager', 12),
  ('vendors', 'Biorepository Manager', 13),
  -- financial
  ('financial', 'Contracts Manager', 1),
  ('financial', 'Clinical Contracts Specialist', 2),
  ('financial', 'Site Budget Specialist', 3),
  ('financial', 'Grants Manager', 4),
  ('financial', 'Clinical Finance Manager', 5),
  ('financial', 'Accounts Payable Specialist', 6),
  ('financial', 'Clinical Payments Manager', 7),
  -- governance
  ('governance', 'Steering Committee Chair', 1),
  ('governance', 'Steering Committee Member', 2),
  ('governance', 'Scientific Advisory Board Member', 3),
  ('governance', 'Endpoint Adjudication Committee Member', 4),
  ('governance', 'Safety Monitoring Committee Member', 5),
  ('governance', 'Protocol Review Committee Member', 6),
  -- technology
  ('technology', 'CTMS Administrator', 1),
  ('technology', 'EDC Administrator', 2),
  ('technology', 'eTMF Manager', 3),
  ('technology', 'Clinical Systems Architect', 4),
  ('technology', 'Clinical Data Integration Specialist', 5),
  ('technology', 'AI Analytics Specialist', 6)
) AS r(cat_code, name, ord) ON c.code = r.cat_code
ON CONFLICT (category_id, name) DO NOTHING;
